### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by guchengxi1994** [Ailln/rasa-guotie#1]
1） readme 里边，rasa trainq 应该时 rasa train 吧

2） windows 上 使用 rasa 载入模型特别慢，不知道这是不是普遍现象

3） utils/data_utils.py  `return yaml.load(data_path.open(encoding='utf-8'))` 改成这样，不然 windows 下可能会有编码问题

4） 多人多轮应答怎么实现（rasa新手，现在用你的这个demo好像时没办法实现 多人多轮 应答）

**Comment by Ailln** [comment]
1. 这里是我不小心打错了；
2. 在 Mac 和 Linux 上也不快，我猜应该是 tensorflow 的原因；
3. 这个问题我会更新在下个版本里；
4. 我好像没有校验用户，其实应该是可以的，回头考虑一下。

感谢反馈～

**Comment by Ailln** [comment]
@guchengxi1994 针对你说的（4）我进行了测试，是可以做到多人多轮的，他默认会认为每个访问者是一个单独的用户，它的 API 中也有 sender 这个概念，不同的 sender 相互独立。你可以打开多个浏览器的匿名窗口进行测试。

**Comment by guchengxi1994** [comment]
@Ailln 这个demo最后是用` rasa x` 指令启动的还是你自己写的前端？我这边起了后台的服务用 postman 测试好像是不能多人多轮

**Comment by guchengxi1994** [comment]
我用 ngrok 实现了多用户的问题，谢谢你的回答

**Comment by Ailln** [comment]
前端是 rasa x 的启动的。
